name: code_connect_frontend
description: "A new Flutter project."
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rust_core: ^0.3.6

  code_connect_common:
    path: ../common
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
