name: code_connect_frontend
description: "A new Flutter project."
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rust_core: ^0.3.6

  code_connect_common:
    path: ../common
  dio: ^5.4.1
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.0+1

flutter:
  uses-material-design: true

  assets:
    - .env
