name: code_connect_backend
description: Code Connect server side application.
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  code_connect_common:
    path: ../common
  collection: ^1.18.0
  dart_openai: ^5.1.0
  dio: ^5.4.1
  dotenv: ^4.2.0
  json_annotation: ^4.8.1
  rust_core: ^0.3.6
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  uuid: ^4.3.3

dev_dependencies:
  shelf_router_generator: ^1.1.0
  build_runner: ^2.4.8
  http: ^1.1.0
  test: ^1.24.0
  json_serializable: ^6.7.1
