name: code_connect_common
description: A starting point for Dart libraries or applications.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  dio: ^5.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  test: ^1.24.0
